management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true


logging:
  file:
    name: /var/log/app/app.log
  level:
    root: INFO
    com.example.demo: DEBUG
