spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-wild-sun-a83wrz56-pooler.eastus2.azure.neon.tech:5432/spring?sslmode=require
spring.datasource.username=spring_owner
spring.datasource.password=npg_GW5jIenPsQM6
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#redis Config
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8081


management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.system=true
management.metrics.enable.tomcat=true
management.metrics.enable.hikaricp=true

